version: 2
updates:
- package-ecosystem: 'npm'
  directory: '/'
  schedule:
    interval: 'daily'
    time: '04:00'
  open-pull-requests-limit: 3
  reviewers:
  - 'nbprojekt'
  assignees:
  - 'nbprojekt'
  labels:
  - 'Dependencies'
  ignore:
  - dependency-name: '@angular*'
    versions:
    - '^9.0.0'
