name: Github CD
on:
  release:
    types:
      - published

jobs:
  lint:
    if: "!(contains(github.event.head_commit.message, 'skip ci') || contains(github.event.pull_request.title, 'wip') || github.event.pull_request.draft)"
    name: Run typescript linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npx ng lint

  build:
    if: "!(contains(github.event.head_commit.message, 'skip ci') || contains(github.event.pull_request.title, 'wip') || github.event.pull_request.draft)"
    name: Run angular production build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Build production
      run: npx ng build --prod

  test:
    if: "!(contains(github.event.head_commit.message, 'skip ci') || contains(github.event.pull_request.title, 'wip') || github.event.pull_request.draft)"
    name: Run karma unit test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Unit tests
      run: npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI

  deploy:
    if: "!(contains(github.event.head_commit.message, 'skip ci') || contains(github.event.pull_request.title, 'wip') || github.event.pull_request.draft)"
    name: Deploy Step
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
    - name: Install dependencies
      run: echo "Deploy Step need to be implemented"
      
